### ISSUE TITLE
README links broken

### ISSUE THREAD

**Issue by Ramblurr** [thi-ng/geom#100]
As a new comer to this set of libs I was trying to get a handle on where to start, but unfortunately most of the README links are broken:

Example: https://github.com/thi-ng/geom/blob/feature/no-org/src/thi/ng/geom/core

..from: https://github.com/thi-ng/geom/blob/feature/no-org/README.org?plain=1#L219-L299

**Comment by kxygk** [comment]
You need to switch to the `master` branch for things to work

It's just a quirk of the library history. The library used to be written in a literate org-mode which then "compiled" into the source code of library. This made the code self-documenting and nice, but very few people bothered setting up the workflow and so there were very few contributors

The library was then converted to a more typical source + docs model - by simply uploading the "compiled" org files on a separate branch. This is the default `no-org` branch you see on the landing page. The net result is it broke all the doc links. There is a lot of documentation... and basically nobody has bothered to go through it all and fix it. If you want non-broken docs you need to switch branches

**Comment by postspectacular** [comment]
@kxygk — Thank you for clarifying this (spot on summart!) and reminding me of this situation! 🙏

**Comment by kxygk** [comment]
I used the library regularly :)) @postspectacular 
Really appreciate all the thought you put into it. It's been a real pleasure to extend when I hit areas where I need new features (mostly when it comes to generating plots and maps)

Happy to know you still have eyeballs on it. I mostly collect small changes into a helper library but I was thinking to make some small PRs to the core (ex: `abs` has been part of `clojure.core` since `1.11`  so i could remove `thi.ng.math.core/abs` and remove some warnings I get)

**Comment by dimovich** [comment]
@Ramblurr besides the link you posted, are there any other that don't work? This seems to be the only one.

Could be changed to:
https://github.com/thi-ng/geom/blob/feature/no-org/src/thi/ng/geom/
