### ISSUE TITLE
WebGL+morphogen demo doesn't work with current morphogen

### ISSUE THREAD

**Issue by skrat** [thi-ng/geom#22]
Additionally, morphogen depends on an outdated version of `thi-ng.geom`. Trying to get this working but no luck so far.

**Comment by postspectacular** [comment]
Hi @skrat, this demo and others will soon be moved into the [thi-ng/demos](https://github.com/thi-ng/demos) repo, since that will make it easier managing the different dependencies needed for each demo. In the meantime I'll take a peek to see if there's a workaround - AFAIK there shouldn't be any incompatibilities, but I might be wrong (haven't use morphogen myself in the past couple of months). Please stand by :)

**Comment by postspectacular** [comment]
I've just pushed a 0.2.0-SNAPSHOT release of morphogen, which now depends on latest geom (0.0.815, also pushed just earlier) - will hopefully get to migrating the demo this week...

**Comment by skrat** [comment]
Amazing, keep it up. Can't wait to see it working with WebGL

**Comment by postspectacular** [comment]
Just found a link to this specific demo in my archive: http://dev.thi.ng/20140523b/ - will get to update it soon...

**Comment by postspectacular** [comment]
Btw. we updated this demo during the Berlin workshop in Feb, but after the recent refactoring over the past month, morphogen is now in dire need to be updated as well... it's on the todo list, but due to an already filled up April likely not to happen before May...

https://github.com/thi-ng/ws-bln-1/blob/master/day2-webgl/src/day2/webgl.cljs

**Comment by postspectacular** [comment]
Just for the record here: I've just pushed a new `0.2.0-SNAPSHOT` of morphogen, which depends on latest thi.ng/geom (1.0.0-RC3), so at least this part is fixed. Demo will be fixed as part of the [thi.ng/demos](https://github.com/thi-ng/demos) repo update.
