### ISSUE TITLE
converting sphere to mesh produces incomplete mesh

### ISSUE THREAD

**Issue by gonewest818** [thi-ng/geom#32]
Some of the triangles are missing, e.g.

```
(ns foo.core
  (:require [thi.ng.geom.sphere :as sphere]
            [thi.ng.geom.core :as g]))

(def sm (-> (sphere/sphere 2) (g/as-mesh {:res 3})))

(count (:faces sm)) ;; ==> 9
```

Visual inspection of the mesh in a stl viewer shows 3 triangles at each of the "poles". It seems there ought to be 6 triangles around the "equator", but I see only 3, leaving three holes.

**Comment by gonewest818** [comment]
Never mind.  Those missing faces are actually quads not being dealt with properly by the stl writer.  Solved by tessellating prior to writing out the stl.

    (def sm (-> (sphere/sphere 2) (g/as-mesh {:res 3}) (g/tessellate)))

**Comment by postspectacular** [comment]
Was just going to tell you that... :) The issue is that I need to update the docstring for `mesh.io/write-stl`, which is still stating that tessellation happens automatically. this feature was removed for performance reasons a over a year ago...

https://github.com/thi-ng/geom/blob/master/geom-meshops/src/meshio.org#stl

**Comment by jackrusher** [comment]
```
(def nef (mio/read-stl (io/input-stream "nefertiti.stl")))
(mio/write-stl (io/output-stream "nef.stl") nef)
```

... results in `nef.stl` missing a few polygons here and there. Would I need to tesselate before save even though I just loaded it?

**Comment by postspectacular** [comment]
hey @jackrusher - I'm surprised you could load the file in the first place, since I've changed the behavior of the mesh.io fns in order to allow I/O also from CLJS (via `ArrayBuffer` objects). *All* of the `mio/read-xxx` and `mio/write-xxx` fns require their stream args to be wrapped like this:

```clj
(def nef (-> "nefertiti.stl" io/input-stream mio/wrapped-input-stream mio/read-stl))
(-> "nef.stl" io/output-stream mio/wrapped-input-stream (mio/write-stl nef))
```
The stream wrappers are from here: https://github.com/thi-ng/dstruct/blob/master/src/streams.org

Almost a year ago I also changed `write-stl` to require pre-tessellation, but only updated the docstring couple of days ago (and on a dev branch not yet on GH). But in your case it really shouldn't be necessary. If you still got issues with it, can you please upload your project & mesh somewhere?

**Comment by postspectacular** [comment]
@jackrusher - what version of geom are you using? I was referring to 0.0.908... :)

**Comment by postspectacular** [comment]
@jackrusher - just verified:

![](http://dev.thi.ng/geom/20160224-nefertiti.png)

**Comment by jackrusher** [comment]
It looks like I'm using `geom` version 0.0.815 because that's what's bundled into `luxor` version 0.3.1.

**Comment by postspectacular** [comment]
I always specify all libraries for a project explicitly to exactly avoid these issues. So instead of relying on luxor pulling in geom (and without knowing which one of the 2 is more recent), it's always more safe to list them both...

**Comment by jackrusher** [comment]
Ah, so. I'm normally a bit concerned that there will be mysterious incompatibilities between, say, geom-X's idea of what a mesh is and luxor-X's idea of the same. If you tell me that the versions in clojars are always compatible with each other, I shall cease worrying. :)

**Comment by postspectacular** [comment]
*Usually* they are and luxor is not dealing with meshes directly. However, the next geom release will have another major restructure and will trigger changes in luxor & morphogen too. Basically, currently working on new mesh type with support for arbitrary vertex attributes (e.g. colors, UV coords for texture mapping etc.)- but in order to not introduce special treatment for this, the existing mesh types are also undergoing a few (minor) changes...
