### ISSUE TITLE
[CLJS] `lin-tick-marks` with `0` delta causes overflow

### ISSUE THREAD

**Issue by acron0** [thi-ng/geom#46]
Hi Karsten, just tracked down this error after tracing it to `linear-axis` in `thi.ng.geom.viz.core`. 
In Java an exception is thrown, but in browser (Chrome, at least) it just overflows and ramps the memory usage up super quick. Happy to PR if you'd advise on how you'd like it fixed. Zero check and empty list return?

``` clojure
(defn lin-tick-marks
  [[d1 d2] delta]
  (if (zero? delta)
    '()
    (let [dr (- d2 d1)
          d1' (m/roundto d1 delta)]
      (filter #(do (println % (m/in-range? d1 d2 %))
                   (m/in-range? d1 d2 %)) (range d1' (+ d2 delta) delta)))))
```

**Comment by postspectacular** [comment]
Good find, Anthony! Yeah, PR would be welcome & looks good (though I would rather use `(m/delta= delta 0.0 m/*eps*)` instead of `(zero? delta)`... (also see [here](https://github.com/thi-ng/math/blob/master/src/core.org#piecewise-and-recursive-equality-check-with-ε-value))

How did you end up with a delta=0 though in the first place? Only mapping a single value? Or if on Y-axis, all values the same?

**Comment by acron0** [comment]
There was a bug in my code which was leading to a 0 delta - as you guessed, same values on a Y-axis :) PR en route
