### ISSUE TITLE
Transparent (de)serialization

### ISSUE THREAD

**Issue by rrrnld** [thi-ng/geom#95]
Are the readers meant to enable completely transparent (de-)serialization?

``` clojure
(update (c/circle 10) :p g/translate [0 100])
;; => {:p [0.0 100.0], :r 10.0}

(update #thi.ng.geom.types.Circle2{:p [0.0 0.0] :r 10.0} :p g/translate [0.0 100.0])
;; Unhandled java.lang.IllegalArgumentException
;;   No implementation of method: :translate of protocol:
;;   #'thi.ng.geom.core/ITranslate found for class: clojure.lang.PersistentVector
```
I was bitten by the fact that the circle's center `:p` is deserialized as a `PersistentVector`, meaning that I could not operate on it without explicitly converting them with `(update c :p v/vec2)`. The behavior is consistent across different geometry types:

``` clojure
(type (:p #thi.ng.geom.types.Rect2{:p [100.0 100.0] :size [100.0 100.0]}))
;; => clojure.lang.PersistentVector
```

I'm not sure how those readers are implemented or how much of a say one has over how those fields are deserialized; they are printed as vectors, so this may as well be intentional. I feel like it would smooth out the API (and enable interesting applications) if one could just treat all geometries as data and transparently encode and decode them.

Alternatively it may be an idea to implement the geom ops for plain `PersistentVector`s, even though I imagine you'd pay a performance penalty at least for the first operation. Has this been discussed before?

Thanks again for this library, it helped me out with  a christmas present this year. :)

**Comment by postspectacular** [comment]
Hey @heyarne! I don't remember the specifics, but serialization related to `pr-writer` & `print-method` stuff used to be semi-magic, undocumented and had some weird quirks & differences between CLJ & CLJS. It seems things have changed/improved since 2014 😄 ... We could try adding the following multimethod impls and test/experiment more with those:

```clj
(require '[thi.ng.geom.vector :as v])

(defmethod print-method thi.ng.geom.vector.Vec2 [a ^java.io.Writer w]
  (.write w (print-str "#vec2" (.toString a))))

(defmethod print-method thi.ng.geom.vector.Vec3 [a ^java.io.Writer w]
  (.write w (print-str "#vec3" (.toString a))))

(v/vec2 10 20)
; #vec2 [10.0 20.0]
```

Testing this with `*data-readers*` seems to work now:

```clj
(require
  '[thi.ng.geom.core :as g]
  '[thi.ng.geom.circle :as c])

(def readers {
  'thi.ng.geom.types.Circle2 c/circle
  'vec2 v/vec2
})

(def foo (binding [*data-readers* readers]
  (read-string (pr-str (c/circle 100)))))
; #'user/foo

foo
; #thi.ng.geom.types.Circle2{:p #vec2 [0.0 0.0], :r 100.0}

(g/as-polygon foo 3)
; #thi.ng.geom.types.Polygon2{:points [#vec2 [100.0 0.0] #vec2 [-49.99999999999998 86.60254037844388] #vec2 [-50.00000000000004 -86.60254037844383]]}
```

I haven't got bandwidth to test this further right now, but if you do and find it's working, then I'd be grateful for a PR. Also related to this (and nice for UX/DX) would be [adding a `data_readers.cljc` file](https://clojuredocs.org/clojure.core/*data-readers*)...

**Comment by dimovich** [comment]
Hello @postspectacular, @heyarne.

As per the official guide (https://clojure.org/reference/reader#tagged_literals)
"Reader tags without namespace qualifiers are reserved for Clojure."

So maybe `#vec2` can be changed to `#thi.ng/vec2`?


It seems `print-method` definitions are only needed for the Clojure part of vectors.
For ClojureScript, vectors already implement IPrintWithWriter
https://github.com/thi-ng/geom/blob/feature/no-org/src/thi/ng/geom/vector.cljc#L361-L364


The code you tried for the data readers:
`{'thi.ng.geom.types.Circle2 c/circle}`

will only work in Clojure because the reader will automatically initialize the record without calling the function you specified. But if you try to run this in ClojureScript, `c/circle` will be called with a map, and will return:
`#thi.ng.geom.types.Circle2{:p [0 0], :r {:p [0 0], :r 100}}`.

The proper way would be to use the automatically generated `map->Circle2` function.

`'thi.ng.geom.types.Circle2 thi.ng.geom.types/map->Circle2`


I've made the proposed changes in my local repository. It needs more testing but so far it seems to work and I can send a PR -- https://github.com/dimovich/geom/commit/e0aa76a3e539ad9dc91a5ea9876188aa909e8538

**Comment by postspectacular** [comment]
Thanks, @dimovich - sure my Clojure foo is slowly getting rusty! I had a hunch about `map->Circle2` probably being the right choice, but only quickly tested this in the Clojure REPL and it seemed to work... These changes look good & thank you for offering a PR, looking forward to it!
